### ISSUE TITLE
ErroDomain error 6 for ios

### ISSUE THREAD

**Issue by saurabhs70** [square/SquarePointOfSaleSDK-iOS#51]
Hi,
we are trying to use Square-Point of sale for iOS still getting error,even if we new signup and Activated account too,why each time getting user not Activated,please help us code are following below.

`NSURL *const callbackURL = [NSURL URLWithString:@"callback://"];

SCCMoney *const amount = [SCCMoney moneyWithAmountCents:1 currencyCode:@"USD" error:NULL];

[SCCAPIRequest setClientID:@"sqxxxid"];

SCCAPIRequest *request = [SCCAPIRequest requestWithCallbackURL:callbackURL
                                                        amount:amount
                                                userInfoString:nil
                                                    merchantID:nil
                                                         notes:@"Coffee"
                                                    customerID:nil
                                          supportedTenderTypes:SCCAPIRequestTenderTypeAll
                                             clearsDefaultFees:NO
                               returnAutomaticallyAfterPayment:NO
                                                         error:nil];

[SCCAPIConnection performRequest:request error:nil];`

![activated](https://user-images.githubusercontent.com/17975720/28521696-724a5688-7092-11e7-89ce-dcd300debd20.png)
![errorcode](https://user-images.githubusercontent.com/17975720/28521706-794df9a8-7092-11e7-982d-e94b95533c93.png)

**Comment by jhankin** [comment]
Hi there, what country is your account from?  If it's a country other than the US, Canada, Japan, Australia, or the UK, and you pass `SCCAPIRequestTenderTypeAll` or `SCCAPIRequestTenderTypeCreditCard`, you will see this message because you cannot use your account to process card payments.  

Can you take a $1 payment with a credit card from the Point of Sale app itself, without using the API?
