### ISSUE TITLE
iOS 13 failing to get a SCCAPIResponse 

### ISSUE THREAD

**Issue by Reycv9** [square/SquarePointOfSaleSDK-iOS#72]
When the app redirects to the Square POS app to complete the transaction after printing the receipt it opens the app. To complete the transaction on our side we require the transaction id which is passed in the SCCAPIResponse. Its failing and not getting the response.. Below is where the code is failing in the App Delegate:

---------------------------------------------------------------------------------------------

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        guard let sourceApplication = options[.sourceApplication] as? String,
            sourceApplication.hasPrefix("com.squareup.square") else {
                return false
        }
        
        do {
            let response = try SCCAPIResponse(responseURL: url)
            if response.isSuccessResponse {
                if let transID = response.transactionID{
                    transactionID = transID
                }
                print("Request succeeded: \(response)")
              
            } else if let errorToPresent = response.error {
                print("Request failed: \(errorToPresent.localizedDescription)")
            }
        } catch let error as NSError {
            print("Request failed: \(error.localizedDescription)")
        }
        return true
    }

**Comment by jmannau** [comment]
I just encountered this too.  According to the [Apple Docs ](https://developer.apple.com/documentation/uikit/uiapplication/openurloptionskey/1623128-sourceapplication) 

>  If the team identifier of the originating app is different than the team identifier of the current app, the value of the key is nil

Given the Square POS app is from a different team, the sourceApplication will be `nil`. This behaviour has changed in iOS 13.  To get around this, I use a specific path for the square callback url: ie: `myapp://square-response` an instead of checking the `sourceApplication.hasPrefix("com.squareup.square")`  I use `url.hasPrefix("myapp://square-response")`

**Comment by MikeSilvis** [comment]
Generated https://github.com/square/SquarePointOfSaleSDK-iOS/pull/75 to assist with this issue

**Comment by MikeSilvis** [comment]
This is now resolved with the latest release! Thanks for your help
